### PR TITLE
Add Kitware's SMQTK to catalogue

### PR DESCRIPTION
**Pull request by Purg**
Pending approval very soon. Will comment again when approved.

### CODE REVIEW

**Comment by Purg** [comment]
OK, yeah, everything is OK on our side. Please merge.

**Comment by tmycann** [comment]
In future commits, please remember we can only accept ascii characters in the catalog.

**Comment by Purg** [comment]
Ooops! That was my mistake for not checking the content that I copy-pasted from thoroughly enough. I think I may have made the same mistake in #239. I assume we're talking about the non-ASCII apostrophe character?

**Comment by tmycann** [comment]
That's correct. I fixed it after having merged both. :)

**Pull request merged**
